web:
  build: .
  command: docker/web/startup.sh
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - mysql
    - ldap

mysql:
  image: mysql:5.6
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true

ldap:
  image: "osixia/openldap"
  ports:
    - "389:389"
    - "636:636"
  volumes:
    - ./doc/ldap:/mnt
